lmhome_v01/lmhome/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lmhome.views.home', name='home'),
    # url(r'^lmhome/', include('lmhome.foo.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^publications/', include('publications.urls', namespace="publications")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

lmhome_v01/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
    )

lmhome_v01/publications/urls.py
from django.conf.urls import patterns, url

from publications import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<publication_id>\d+)/$', views.detail, name='detail'),
    #url(r'^(?P<publication_id>\d+)/vote/$', views.vote, name='vote'),
    )

lmhome_v01/polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Poll(models.Model):

  question = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date published')

  def __unicode__(self):
    return self.question

  def was_published_recently(self):
    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
  was_published_recently.admin_order_field = 'pub_date'
  was_published_recently.boolean = True
  was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
  
  poll = models.ForeignKey(Poll)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)

  def __unicode__(self):
    return self.choice_text

lmhome_v01/publications/models.py
from django.db import models
from django.utils import timezone
import datetime

class Publisher(models.Model):
  name = models.CharField(max_length=200)
  abbrev = models.CharField(max_length=30)
  impact_factor = models.DecimalField(max_digits=5, decimal_places=3)
  punkty_mnsw = models.IntegerField(default=0)
  website = models.URLField()

  def __unicode__(self):
    return self.abbrev
  
  class Meta:
    ordering = ('name',)

class Author(models.Model):
  first_name = models.CharField(max_length=40)
  last_name = models.CharField(max_length=40)
  email = models.EmailField()

  def __unicode__(self):
    return u'%s %s' % (self.first_name, self.last_name)

  class Meta:
    ordering = []#('last_name',)

class Publication(models.Model):
  authors = models.ManyToManyField(Author)
  title = models.CharField(max_length=500)
  publisher = models.ForeignKey(Publisher)
  volume = models.IntegerField(default=0)
  page = models.CharField(max_length=10)
  pub_date = models.DateField()
  abstract = models.TextField(blank=True)
  doi = models.CharField(max_length=100,blank=True)
  www = models.URLField(blank=True)
  arxiv = models.CharField(max_length=20,blank=True)
  info = models.TextField(blank=True)

  def __unicode__(self):
    return self.title

  class Meta:
    ordering = ('-pub_date',)

  def was_published_this_year(self):
    dt = datetime.datetime.combine(self.pub_date, datetime.time(0,0))
    t = timezone.now()
    return dt > t.astimezone(timezone.utc).replace(tzinfo=None) - datetime.timedelta(days=365)
  was_published_this_year.admin_order_field = 'pub_date'
  was_published_this_year.boolean = True
  was_published_this_year.short_description = 'Published within a year?'

lmhome_v01/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from polls.models import Poll

def index(request):
  latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
  template = 'polls/index.html'
  context = {'latest_poll_list': latest_poll_list,}
  return render(request, template, context)

def detail(request, poll_id):
  try:
    poll = Poll.objects.get(pk=poll_id)
  except Poll.DoesNotExist:
    raise Http404
  return render(request, 'polls/detail.html', {'poll': poll})

def results(request, poll_id):
  poll = get_object_or_404(Poll, pk=poll_id)
  return render(request, 'polls/results.html', {'poll': poll})

def vote(request, poll_id):
  p = get_object_or_404(Poll, pk=poll_id)
  try:
    selected_choice = p.choice_set.get(pk=request.POST['choice'])
  except (KeyError, Choice.DoesNotExist):
    return render(request, 'polls/detail.html', {
      'poll': p,
      'error_message': "wybierz choice",
      })
  else:
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

lmhome_v01/publications/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from publications.models import Publication

def index(request):
  _list = Publication.objects.order_by('-pub_date')
  _nums = range(1,len(_list)+1)
  all_publications_dict = dict(zip(_nums[::-1],_list))
#  lfn = u'%s'%first_name
#  first_letters = "".join([i[:1]+"." for i in lfn.split(' ')])

  template = 'publications/index.html'
  context = {'all_publications_dict': all_publications_dict,}
  
  return render(request, template, context)

def detail(request, publication_id):
  try:
    publication = Publication.objects.get(pk=publication_id)
  except Publication.DoesNotExist:
    raise Http404
  return render(request, 'publications/detail.html', {'publication': publication})

lmhome_v01/polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote">
</form>

lmhome_v01/polls/templates/polls/index.html
{% if latest_poll_list %}
  <ul>
  {% for poll in latest_poll_list %}
  <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>Nie ma zadnych polls-ow</p>
{% endif %}

lmhome_v01/polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<ul>
{% for choice in poll.choice_set.all %}
<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">U wanna wote again?</a>

lmhome_v01/publications/templates/publications/detail.html
{% include "publications/header.html" %}

<div class="breadcrumb"><a href="../">to the list of publications</a></div>
<hr>
<p class="pub_title">{{ publication.title }}</p>
<p class="citation"><i>{{ publication.publisher }}</i> <strong>{{ publication.volume }}</strong>, 
{{ publication.page }} ({{ publication.pub_date.year }})</p>

<ul>
{% for author in publication.authors.all %}
<li>{{ author.first_name }} {{ author.last_name }}, <a href="mailto:{{ author.email }}">{{ author.email }}</a></li>
{% endfor %}
</ul>

<div class="get_article">
  {% if publication.doi %}
  doi:<a href="http://dx.doi.org/{{ publication.doi }}" target=_blank>{{ publication.doi }}</a> 
  {% else %}
  www:<a href="{{ publication.www }}" target=_blank>{{ publication.www }}</a> 
  {% endif %}
  | 
  arxiv:<a href="http://arxiv.org/abs/{{ publication.arxiv }}" target=_blank>{{ publication.arxiv }}</a>
  |
  <span class="pdf">PDF</span> 
</div>
<div class="abstract">
  <p class="abstract-title">Abstract</p>
  <p class="abstract-body">{{ publication.abstract }}</p>
</div>

<div class="journal_info">
  impact factor {{ publication.publisher.impact_factor }} | MNiSW points {{ publication.publisher.punkty_mnsw }}
</div> 

{% include "publications/footer.html" %}

lmhome_v01/publications/templates/publications/footer.html
</div>
</div>
<div id="footer">
  &copy; 2013, <a href="mailto:lukasz.machura@us.edu.pl">Łukasz Machura</a>,  
  Department of Theoretical Physics, Institute of Physics,
  University of Silesia,
  ul. Uniwersytecka 4, 40-007 Katowice
</div>
</body>

lmhome_v01/publications/templates/publications/header.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<link rel="stylesheet" type="text/css" href="{% static 'publications/style.css' %}" />
<title>LM's pages</title>
</head>
<body>
  <div id="container">
    <div id="top">dr Łukasz Machura</div>
    <div id="main">

lmhome_v01/publications/templates/publications/index.html
{% include "publications/header.html" %}

<p class="pub_title">List of publications</p>
<ol>
  {% for key, pub in all_publications_dict.items %}
  <li value="{{ key }}"><a href="{% url 'publications:detail' pub.id %}">{{ pub.title }}</a>
  <br />
  {% for author in pub.authors.all %}
  {% if author.last_name == "Machura" %}
  <strong>
    {{ author.first_name }} {{ author.last_name }},
  </strong>
  {% else %}
    {{ author.first_name }} {{ author.last_name }},
  {% endif %}
  {% endfor %}
  <br />{{ pub.publisher.abbrev }} <strong>{{ pub.volume }}</strong>, {{ pub.page }} ({{ pub.pub_date.year }}).
  </li>
  {% empty %}
  <p>Nie ma zadnych publikacji</p>
  {% endfor %}
</ol>

{% include "publications/footer.html" %}